### ISSUE TITLE
Do you understand Django?

### ISSUE THREAD

**Issue by jbrucker** [Hamiz5401/ku-polls#22]
Suggestion for your poll question.

question: "How well do you understand Django?"

Choices:

- [ ] Very well: can create an app with many models and views from scratch
- [ ] Somewhat: can create an app, but still have trouble with some parts
- [ ] Not much
- [ ] Not at all (*add a hint what this means*)
- [ ] Do you mean the rock band *Django*?

**Comment by Hamiz5401** [comment]
That question was added as a joke so I didn't think much about the choices(Sry for adding a trivia question) but I'll change the choices according to your suggestion.

- This issues will be fix today

**Comment by Hamiz5401** [comment]
Change "Do you understand Django?" polls according to your suggestions

**Comment by jbrucker** [comment]
It's one of the two required questions you submitted, so joke or not it counts.

it's more interesting than some questions that others have submitted.
